name: notes_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  hexcolor: ^3.0.1
  # stylish_bottom_bar: ^1.0.3
  # convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.2.1
  jiffy: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf


